# Generated by Django 2.2.3 on 2019-07-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image in background in history activity')),
                ('description', models.TextField(verbose_name='Description of history')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Number/Name of version')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.History', verbose_name='Which history unlock this set')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.Version', verbose_name='In which version this set is included')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_1', models.IntegerField(choices=[(1, 'Giraffe'), (2, 'Elephan'), (3, 'Lion'), (4, 'Lizard'), (5, 'Camel')], verbose_name='First box')),
                ('box_2', models.IntegerField(choices=[(1, 'Giraffe'), (2, 'Elephan'), (3, 'Lion'), (4, 'Lizard'), (5, 'Camel')], verbose_name='Second box')),
                ('box_3', models.IntegerField(choices=[(1, 'Giraffe'), (2, 'Elephan'), (3, 'Lion'), (4, 'Lizard'), (5, 'Camel')], verbose_name='Third box')),
                ('box_4', models.IntegerField(choices=[(1, 'Giraffe'), (2, 'Elephan'), (3, 'Lion'), (4, 'Lizard'), (5, 'Camel')], verbose_name='Fourth box')),
                ('box_5', models.IntegerField(choices=[(1, 'Giraffe'), (2, 'Elephan'), (3, 'Lion'), (4, 'Lizard'), (5, 'Camel')], verbose_name='Fifth box')),
                ('two_star_time', models.FloatField(verbose_name='Time to reach result with two star (2*)')),
                ('three_star_time', models.FloatField(verbose_name='Time to reach result with three star (3*)')),
                ('perfect_move_count', models.IntegerField(verbose_name='Maximum number of move to reach special star')),
                ('order', models.IntegerField(verbose_name='Number of level in set')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.Set', verbose_name='Pointer to set where level is located')),
            ],
            options={
                'ordering': ['-set', 'order'],
            },
        ),
    ]
