# Generated by Django 2.2.3 on 2019-07-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='title',
            field=models.CharField(default='Test', max_length=250, verbose_name='History title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='title',
            field=models.CharField(default='Test', max_length=250, verbose_name='Set title'),
            preserve_default=False,
        ),
    ]
