# Generated by Django 2.2.3 on 2019-07-30 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20190728_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='version',
            name='next_version',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_available_version', to='updates.Version'),
        ),
    ]
